name: Robot Framework UI Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  robot-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Google Chrome and ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip xvfb
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo dpkg -i google-chrome-stable_current_amd64.deb || sudo apt-get -fy install
        LATEST=$(curl -sSL https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
        wget https://chromedriver.storage.googleapis.com/$LATEST/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        chmod +x chromedriver
        sudo mv chromedriver /usr/local/bin/

    - name: Run Robot Framework tests
      run: |
        Xvfb :99 -ac &
        export DISPLAY=:99
        robot test/SanityTest.robot

    - name: Upload Robot Report
      uses: actions/upload-artifact@v4
      with:
        name: robot-report
        path: |
          output.xml
          report.html
          log.html
